---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 1000
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown -R 1000:1000 /mnt/media"]
          volumeMounts:
            - name: media
              mountPath: /mnt/media
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          ports:
            - containerPort: 7878
              name: http
          env:
            - name: PUID
              value: "1000" # Рекомендуется использовать Kubernetes Secrets или ConfigMaps для конфиденциальных данных
            - name: PGID
              value: "1000" # Рекомендуется использовать Kubernetes Secrets или ConfigMaps для конфиденциальных данных
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /mnt/media
          livenessProbe:
            httpGet:
              path: /api/v3/system/status
              port: 7878
              httpHeaders:
                - name: X-Api-Key
                  value: "900649c1dd444f199ebfb913431ec0b6"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v3/system/status
              port: 7878
              httpHeaders:
                - name: X-Api-Key
                  value: "900649c1dd444f199ebfb913431ec0b6"
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: config
          hostPath:
            path: /SSD/app-data/radarr
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: /DATA/media
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: radarr
  labels:
    app: radarr
spec:
  selector:
    app: radarr
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      name: webui
      targetPort: 7878
