apiVersion: v2
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 20.0.3
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.5.24
- condition: minio.enabled
  name: minio
  repository: https://charts.bitnami.com/bitnami
  version: 14.7.14
- condition: appflowy-cloud.enabled
  name: appflowy-cloud
  repository: ""
  version: 0.1.0
- condition: appflowy-gotrue.enabled
  name: appflowy-gotrue
  repository: ""
  version: 0.1.0
- condition: appflowy-admin.enabled
  name: appflowy-admin
  repository: ""
  version: 0.1.0
- condition: appflowy-worker.enabled
  name: appflowy-worker
  repository: ""
  version: 0.1.0
- condition: appflowy-web.enabled
  name: appflowy-web
  repository: ""
  version: 0.1.0
- condition: global.ai.enabled
  name: appflowy-ai
  repository: ""
  version: 0.1.0
description: AppFlowy Cloud Helm Chart
name: appflowy
type: application
version: 0.2.1
